/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 football.gltf --transform
Author: chroma3d (https://sketchfab.com/vendol21)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-cartoon-football-ball-free-259ba8af81484d19861fd5d70e9f5fcc
Title: Low Poly Cartoon Football Ball Free
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Football(props: any) {
  const { nodes, materials }: any = useGLTF("/football-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={50}>
        <mesh
          geometry={nodes.FootballBall_White_0.geometry}
          material={materials.White}
        />
        <mesh
          geometry={nodes.FootballBall_Black_0.geometry}
          material={materials.Black}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/football-transformed.glb");
